### ISSUE TITLE
pharmacy raw data + cleaning

### ISSUE THREAD

**Issue by josephholler** [samroubin/VTPharmacy#14]
- [x] remove old raw pharmacy csv from OSF
- [x] upload pharmacy_raw.csv to OSF
- [x] upload Rmd script as 00_pharmacy_cleaning.Rmd to git repo
- [x] update pharmacy_raw.md metadata file
- [x] update animated GIF with final data

**Comment by josephholler** [comment]
@samroubin  : I proofread the report and it looks good. When you're all set with the animation update, I will:

- [x] pull it into CyberGISX
- [x] remove unnecessary packages
- [x] try color-coding catchment areas by time-band
- [x] try calculating the % diff between rural / non-rural in the notebook (caught a small thing in there, so it's better to automate it)
- [x] execute the blocks one more time
- [x] clear output of blocks with any staffing level content
- [x] save HTML version with interactive maps
- [x] enable repository website with report
- [x] save PDF version without interactive maps
- [x] pull changes into the HEGSRR version of the repository
- [x] add Ben to the Kang reproduction citation
- [x] link reports
- [x] register report

**Comment by samroubin** [comment]
Great! Thank you!!

I'm working on all that now - will let you know when all completed. One thing I also noticed is that there is no metadata file for pharmacies_df.gpkg, so I will add that (?). This would essentially be the same metadata as the pharmacies_raw.csv without staffing levels, and it would note that it was created by using the 00_pharmacies_cleaning.Rmd and converted to a .gpkg in QGIS.

**Comment by samroubin** [comment]
Great! Thank you!!

I'm working on all that now - will let you know when all completed. One thing I also noticed is that there is no metadata file for pharmacies_df.gpkg, so I will add that (?). This would essentially be the same metadata as the pharmacies_raw.csv without staffing levels, and it would note that it was created by using the 00_pharmacies_cleaning.Rmd and converted to a .gpkg in QGIS.

-Sam
________________________________

**Comment by josephholler** [comment]
@samroubin Registration done!  Also, see interactive report version here: https://hegsrr.github.io/OR-VT-Pharmacy/

**Comment by josephholler** [comment]
Will update again once registration archiving & DOI are complete, to add DOI to the main readme.

**Comment by samroubin** [comment]
Awesome!! It looks great. Thanks again for making those final changes.

One thing I noticed is that the date modified in the study metadata says 1/11/24. I really thought I updated that recently, but I'm not sure what happened. Probably doesn’t matter too much, but if it's easy maybe it's worth updating? Or would that require reregistering everything?

So excited to have this registered! No rush, but please keep me posted on when your schedule opens up to review the manuscript.

Sam



________________________________

**Comment by josephholler** [comment]
Ah, I changed the date on the HEGSRR version of the repo .readme.  I wish that was automatic.
Also invited you to the HEGSRR organization so that I can add you to that version of the repo. It'd be easiest to continue making any further changes there.
Finally, there was a technical snag with OSF registration that I haven't heard back about. Haven't seen that happen before.
